"""empty message

Revision ID: be530011b9bc
Revises: 919d94f776b1
Create Date: 2026-01-08 06:24:37.187337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be530011b9bc'
down_revision = '919d94f776b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('distance_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_rate')
    # ### end Alembic commands ###
